### ISSUE TITLE
Oem kill does not seem to work anymore

### ISSUE THREAD

**Issue by KoleckOLP** [OpenTabletDriver/Plugin-Repository#17]
Ever since 5.0 or maybe earlier, lauching OTD with OemKill enabled does not stop the Wacom drivers anymore.
Is that my fault Do I need to run the Installer/laucher as admin?
As for now I kill the driver manually in task bar.

**Comment by X9VoiD** [comment]
This is not an issue for Plugin-Repository and should be moved to [VoiDPlugins](https://github.com/X9VoiD/VoiDPlugins)

**Comment by KoleckOLP** [comment]
Okay posted it there.
